// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vBRiL1Wbz0xuVmwv8WD0REO0l4XW2lM',
    appId: '1:912724582568:web:7dd6fe2de77b86a1eda29d',
    messagingSenderId: '912724582568',
    projectId: 'raspberrypi-ab822',
    authDomain: 'raspberrypi-ab822.firebaseapp.com',
    databaseURL: 'https://raspberrypi-ab822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raspberrypi-ab822.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODn1oQeAPLURaoDTrWQ7-VRlNziZt70U',
    appId: '1:912724582568:android:98c8a3b30e6bf51aeda29d',
    messagingSenderId: '912724582568',
    projectId: 'raspberrypi-ab822',
    databaseURL: 'https://raspberrypi-ab822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raspberrypi-ab822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1382oJO_TmWDhAVfrU0F-0pp5gIgZkKs',
    appId: '1:912724582568:ios:55c4e91015baf166eda29d',
    messagingSenderId: '912724582568',
    projectId: 'raspberrypi-ab822',
    databaseURL: 'https://raspberrypi-ab822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raspberrypi-ab822.appspot.com',
    iosClientId: '912724582568-lhkhdc2omttn6pr0jc4147nit04ne72k.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityLockerIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1382oJO_TmWDhAVfrU0F-0pp5gIgZkKs',
    appId: '1:912724582568:ios:55c4e91015baf166eda29d',
    messagingSenderId: '912724582568',
    projectId: 'raspberrypi-ab822',
    databaseURL: 'https://raspberrypi-ab822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raspberrypi-ab822.appspot.com',
    iosClientId: '912724582568-lhkhdc2omttn6pr0jc4147nit04ne72k.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityLockerIot',
  );
}
